AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-auth1

  Sample SAM Template for sam-auth1

Globals:
  Function:
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.3

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuth
        Authorizers:
          MyLambdaTokenAuth:
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Header: Auth
              ValidationExpression: ^a.{3}w$
              # テスト: Authヘッダの内容がa...wでない場合すぐ弾いて(lambdaの資源節約)
              # Unauthorizedにする。
              # 普通はベアラーヘッダ向けに `Bearer.*`

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        Hello:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: get
        Goodbye:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /goodbye
            Method: get
            Auth:
              Authorizer: NONE
              # テスト: override

  HelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: HelloFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${HelloFunction}"

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: auth.handler
      Runtime: nodejs14.x
  MyAuthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: MyAuthFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${MyAuthFunction}"

Outputs:
  HelloApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${MyApi.Stage}/hello/"
